# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: saarthak08/complex-multistage-docker-server
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: " 1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"

---

# CLUSTER-IP-SERVICE
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000