apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 5
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: saarthak08/complex-multistage-docker-client
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          memory: 512Mi
                          cpu: "1"
                      requests:
                          memory: 256Mi
                          cpu: "0.2"
