version: '3'

services: 
  
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on: 
      - redis
      - postgres
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PGUSER=postgres
    - PGHOST=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=postgres_password
    - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    depends_on: 
      - redis
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    depends_on: 
      - api
      - client
    ports: 
      - '3050:80'
